A, B = input().split()
ans = -float('inf')
ans = max(ans, int('9'+A[1:]) - int(B))
ans = max(ans, int(A[0] + '9' + A[2]) - int(B))
ans = max(ans, int(A[:2] + '9') - int(B))
ans = max(ans, int(A) - int('1' + B[1:]))
ans = max(ans, int(A) - int(B[0] + '0' + B[2]))
ans = max(ans, int(A) - int(B[:2] + '0'))
ans = max(ans, int(A) - int(B))
print(ans)
